#!/bin/bash

# scp target/aarch64-unknown-linux-gnu/release/holland2stay-rs matteo@192.168.0.116:/home/matteo/.cargo/bin
rsync -avz --progress target/aarch64-unknown-linux-gnu/release/holland2stay-rs matteo@192.168.0.116:/home/matteo/.cargo/bin/